stages:
  - build
  - deploy


.build-template:
  before_script:
    - $(aws ecr get-login --no-include-email --region eu-central-1)
    - case "$CI_COMMIT_REF_SLUG" in "develop") TAG=stage ;; "master") TAG=latest ;; *) TAG=$CI_COMMIT_REF_SLUG ;; esac
    - echo "$TAG"

include:
  - project: duckness/ci-templates
    file: /common/deploy/docker-compose-to-ec2.v1.1.yml

build-nginx:
  stage: build
  extends: .build-template
  script:
    - cd dockerfiles/nginx && sh build.sh $TAG push
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME || $CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - dockerfiles/nginx/**/*
      when: manual

build-strapi:
  stage: build
  extends: .build-template
  script:
    - cd dockerfiles/strapi && sh build.sh $TAG push
  only:
    - master

prod:
  extends: .docker_compose_to_ec2
  stage: deploy
  needs:
    - build-strapi
  variables:
    ENV_NAME: JCIT
    URL: "cms.justcontrol.it"
    DOCKER_COMPOSE_DST_DIR: "/src/cms"
    DOCKER_COMPOSE_SRC_PATH: "docker-compose-prod.yml"
    MODULES_TO_PULL: "nginx strapi"
    MODULE_TO_START: "strapi"
  before_script:
    - if [ -e success ]; then rm -f success; fi
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME || $CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: manual
      allow_failure: false
