version: "3.7"

networks:
  backend:
    attachable: true


services:
  nginx:
    image: 602044514283.dkr.ecr.eu-central-1.amazonaws.com/jc_site/nginx:latest
    restart: always
    networks:
      - backend
    depends_on:
      - strapi
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/certbot:/var/www/certbot
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    networks:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/certbot:/var/www/certbot

  strapi:
    container_name: strapi
    networks:
      - backend
    dns: 8.8.8.8
    image: 602044514283.dkr.ecr.eu-central-1.amazonaws.com/jc_site/strapi:latest
    env_file: .docker.env
    ports:
      - 1337:1337
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo:5.0
    networks:
      - backend
    dns: 8.8.8.8
    env_file: .docker.env
    ports:
      - 27017:27017
    volumes:
      - /var/lib/cms/mongo/data/db:/data/db
    restart: always
