version: "3"

volumes:
  database:

services:
  strapi:
    container_name: strapi
    image: strapi/strapi:3.6.5
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/srv/app
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo:5.0
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database:/data/db
    restart: always
